name: attest-pack

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-attest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build attestation pack
        shell: pwsh
        continue-on-error: true
        run: |
          pwsh ./ci/make-attestation-pack.ps1

      - name: Ensure out directory
        run: |
          mkdir -p out

      - name: Upload attestation artifact
        if: ${{ hashFiles('out/*.zip') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: humean-attestation
          path: out/*.zip
