name: sign-and-verify

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  sign-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run HUMEAN sign+verify CI
        shell: pwsh
        env:
          HUMEAN_PRIVKEY_B64: ${{ secrets.HUMEAN_PRIVKEY_B64 }}
          HUMEAN_PUBKEY_B64:  ${{ secrets.HUMEAN_PUBKEY_B64 }}
          GITHUB_TOKEN:       ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwsh ./ci/sign-and-verify-ci.ps1
