name: Verify ledger signatures
on:
  push: { branches: [ "main" ] }
jobs:
  verify-ledger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify
        shell: bash
        run: |
          set -euo pipefail
          cat attestation/ledger.log | ssh-keygen -Y verify -f attestation/keys/pub_ed25519.openssh -I humean -n file -s attestation/ledger.sshsig
